### ISSUE TITLE
oxford.py depends on faiss which is not available under Windows

### ISSUE THREAD

**Issue by ewirbel** [almazan/paiss#2]
Hello,

Unless I am mistaken, faiss-cpu conda package does not exist for Windows OS (see https://anaconda.org/pytorch/faiss-cpu). Is there either a channel where the conda package for Windows can be found, or a way to remove that faiss dependency ?

**Comment by rafarez** [comment]
We're currently looking for alternatives for faiss for windows users. For running the demo, you can comment the line 
`import faiss`
on datasets/oxford.py.

**Comment by ewirbel** [comment]
I confirm this works when removing the line for the demo script, thanks.
